### ISSUE TITLE
Images of ravada for the project-site

### ISSUE THREAD

**Issue by Gianfranco97** [TECLIB/ravada#3]
**Is your feature request related to a problem? Please describe.**
We do not have the necessary ravada images

**Describe the solution you'd like**
it is necessary to create the images, they must have the same format as those of Flyve MDM (size, name, and format)

**Additional context**
These are the sample images:
- [images.zip](https://github.com/TECLIB/ravada/files/2320004/images.zip)

**Comment by E1matheus** [comment]
## Aug 28th Update:

* Created new icons for Ravada in svg format using Inkscape. Made some samples in png format.

**Ravada icon sample 1:**
![ravada icon sample 1](https://user-images.githubusercontent.com/38697844/44737195-977a1200-aaf1-11e8-8c59-7a269d71aa07.png)

**Ravada icon sample 2:**
![ravada icon sample 2](https://user-images.githubusercontent.com/38697844/44737214-a365d400-aaf1-11e8-8c87-6491cc7bc79b.png)

**Ravada icon sample 3:**
![ravada icon sample 3](https://user-images.githubusercontent.com/38697844/44737223-ab257880-aaf1-11e8-9c16-d612a8d8ce84.png)

**Comment by E1matheus** [comment]
## Aug 29th Update:

* Alexander told me to aim for a silhouette style for the Ravada icons so it can blend easily with rest of FlyVE Products icons.
* Created a silhouette variant for the Ravada logo in both white and black colors using Inkscape (svg format).
* Created multiple background shapes for the Ravada logo icons: square with simple corners, square with round corners (adding shine and shadows), and square with round corners 
  and hard shadows, using Inkscape (svg format).
* Made some samples in png format.

**Ravada logo (Silhouette - Black):**
![ravada icon silhouette - black sample 1](https://user-images.githubusercontent.com/38697844/44796842-2482a100-abae-11e8-9a63-7a5fa36899db.png)

**Ravada Icon (Square - Simple corners):**
![ravada icon square - simple corners sample 1](https://user-images.githubusercontent.com/38697844/44796856-2f3d3600-abae-11e8-8024-022170fc58a2.png)
![ravada icon square - simple corners sample 2](https://user-images.githubusercontent.com/38697844/44796859-32382680-abae-11e8-86d9-f53a09f3753c.png)
![ravada icon square - simple corners sample 3](https://user-images.githubusercontent.com/38697844/44796865-349a8080-abae-11e8-8d66-425073de8e89.png)
![ravada icon square - simple corners sample 4](https://user-images.githubusercontent.com/38697844/44796870-382e0780-abae-11e8-87c2-8e0b4329d35d.png)

**Ravada Icon (Square - Rounded corners - Shine and Shadows):**
![ravada icon square - rounded corners sample 1](https://user-images.githubusercontent.com/38697844/44796917-53007c00-abae-11e8-85b9-7cd9254cf1f9.png)
![ravada icon square - rounded corners sample 2](https://user-images.githubusercontent.com/38697844/44796923-56940300-abae-11e8-9d7d-30792c1516f1.png)
![ravada icon square - rounded corners sample 3](https://user-images.githubusercontent.com/38697844/44796928-5a278a00-abae-11e8-9c43-907d2f88b176.png)
![ravada icon square - rounded corners sample 4](https://user-images.githubusercontent.com/38697844/44796937-5c89e400-abae-11e8-9590-39a1f62446b1.png)

**Ravada Icon (Square - Rounded corners - Hard Shadows):**
![ravada icon square - rounded corners - hard shadows sample 1](https://user-images.githubusercontent.com/38697844/44796955-66134c00-abae-11e8-8762-8f52bfcc287a.png)
![ravada icon square - rounded corners - hard shadows sample 2](https://user-images.githubusercontent.com/38697844/44796967-69a6d300-abae-11e8-904c-cb00a3357d79.png)
![ravada icon square - rounded corners - hard shadows sample 3](https://user-images.githubusercontent.com/38697844/44796974-6ca1c380-abae-11e8-91b1-d5072a755bcb.png)
![ravada icon square - rounded corners - hard shadows sample 4](https://user-images.githubusercontent.com/38697844/44796984-71ff0e00-abae-11e8-81a3-33a0d95c21cd.png)

**Comment by Gianfranco97** [comment]
@E1matheus  Create one for the UPC, please. Like the one we have in the footer for teclib

**Comment by ajsb85** [comment]
Hi, @E1matheus 
Could you use an Orange instead blue?
Because blue is used for GLPI Network.

![image](https://user-images.githubusercontent.com/663460/44976581-eac2e900-af65-11e8-8dee-437e8517a7c4.png)

![image](https://user-images.githubusercontent.com/663460/44976587-edbdd980-af65-11e8-974e-aecf2a5f1e2e.png)

**Comment by E1matheus** [comment]
## Sep 4th Update:

* Created the new Orange variant set of images for the Ravada Project site replicating the names, format and sizes of the original package.
* Created a new UPC logo for the footer.

### Here's the new set of images for the Ravada Project Site:

* **apple-touch-icon:**
![apple-touch-icon](https://user-images.githubusercontent.com/38697844/45035068-66519280-b059-11e8-8f91-72d538434a87.png)

* **favicon:**
![favicon](https://user-images.githubusercontent.com/38697844/45035098-70739100-b059-11e8-9df2-a0c9f84cf2b4.png)

* **icon-192x192:**
![icon-192x192](https://user-images.githubusercontent.com/38697844/45035113-7ec1ad00-b059-11e8-84b4-28d7e0067a54.png)

* **icon-256x256:**
![icon-256x256](https://user-images.githubusercontent.com/38697844/45035117-82edca80-b059-11e8-90f4-af801fc4c34d.png)

* **icon-384x384:**
![icon-384x384](https://user-images.githubusercontent.com/38697844/45035132-8d0fc900-b059-11e8-92d9-88f3ce8b867b.png)

* **icon-512x512:**
![icon-512x512](https://user-images.githubusercontent.com/38697844/45035142-94cf6d80-b059-11e8-9bf7-60bda79ff596.png)

* **logo3:**
![logo3](https://user-images.githubusercontent.com/38697844/45035176-a6b11080-b059-11e8-8b7e-0f50b3526706.png)

* **logo-ravada:**
![logo-ravada](https://user-images.githubusercontent.com/38697844/45035184-aca6f180-b059-11e8-8dbb-5655b77c44f8.png)

* **typo:** 
![typo](https://user-images.githubusercontent.com/38697844/45035192-b3cdff80-b059-11e8-806a-e3a7069ce1eb.png)

**logo-upc:**
![logo-upc](https://user-images.githubusercontent.com/38697844/45035218-c21c1b80-b059-11e8-9461-49433d783d37.png)


### HERE'S THE .ZIP FILE WITH THE COMPLETE SET
[Ravada image pack (FINAL - ORANGE).zip](https://github.com/TECLIB/ravada/files/2348864/Ravada.image.pack.FINAL.-.ORANGE.zip)

**Comment by E1matheus** [comment]
* Gianfranco asked me to check out the new look of the footer with the new UPC logo, after some consideration we decided to change the letter color from dark gray to black, so they would be more noticeable. I made the correspondent amendment using Inkscape and produced a new png.

Here's the updated UPC logo:
![logo-upc](https://user-images.githubusercontent.com/38697844/45038974-c8fb5c00-b062-11e8-8a5a-85b524afe2ea.png)

HERE'S THE .ZIP FILE WITH THE COMPLETE SET (INCLUDING THE UPDATED UPC LOGO):
[Ravada image pack (FINAL - ORANGE).zip](https://github.com/TECLIB/ravada/files/2349120/Ravada.image.pack.FINAL.-.ORANGE.zip)

**Comment by E1matheus** [comment]
* Corrected a typo on the previous documents, they now say "Ravada VDI":

**English:**
![ravada reference english](https://user-images.githubusercontent.com/38697844/45168560-d861dd00-b1fb-11e8-8e60-691dd211755c.png)

**French:**
![ravada reference french](https://user-images.githubusercontent.com/38697844/45168570-df88eb00-b1fb-11e8-8b4d-b1cea461840c.png)

**Download Links:**
[Ravada logo reference chart.pdf](https://github.com/TECLIB/ravada/files/2357706/Ravada.logo.reference.chart.pdf)
[Logo Ravada référence.pdf](https://github.com/TECLIB/ravada/files/2357707/Logo.Ravada.reference.pdf)
